### ISSUE TITLE
UAParser.js npm Package Supply Chain Attack

### ISSUE THREAD

**Issue by nasifimtiazohi** [IQTLabs/software-supply-chain-compromises#18]
https://www.bleepingcomputer.com/news/security/popular-npm-library-hijacked-to-install-password-stealers-miners/

**Comment by jspeed-meyers** [comment]
Thank you!

**Comment by jspeed-meyers** [comment]
Possibly related: https://blog.sonatype.com/newly-found-npm-malware-mines-cryptocurrency-on-windows-linux-macos-devices
