### ISSUE TITLE
Add SolarWinds/Sunburst

### ISSUE THREAD

**Issue by jorgeorchilles** [IQTLabs/software-supply-chain-compromises#2]
https://www.fireeye.com/blog/threat-research/2020/12/evasive-attacker-leverages-solarwinds-supply-chain-compromises-with-sunburst-backdoor.html

**Comment by jspeed-meyers** [comment]
Thank you, @jorgeorchilles. I will add that to the immediate todo list.

**Comment by bentztozer** [comment]
This has been added to the CSV file.  We'll keep updating as more information is available.
