### ISSUE TITLE
Deparment of Defense Common Access Card Malware - Does this count?

### ISSUE THREAD

**Issue by jspeed-meyers** [IQTLabs/software-supply-chain-compromises#30]
https://krebsonsecurity.com/2022/05/when-your-smart-id-card-reader-comes-with-malware/

I think it does. @bentztozer ???

**Comment by bentztozer** [comment]
I think it does as well.  Do you want me to add it to the list?

Bentz Tozer
In-Q-Tel
Vice President
Cyber Practice
Office:   571.206.0644
Mobile: 571.814.0944

From: John Speed Meyers ***@***.***>
Sent: Thursday, May 19, 2022 8:42 AM
To: IQTLabs/software-supply-chain-compromises ***@***.***>
Cc: Tozer, Bentz ***@***.***>; Mention ***@***.***>
Subject: [IQTLabs/software-supply-chain-compromises] Deparment of Defense Common Access Card Malware - Does this count? (Issue #30)


https://krebsonsecurity.com/2022/05/when-your-smart-id-card-reader-comes-with-malware/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkrebsonsecurity.com%2F2022%2F05%2Fwhen-your-smart-id-card-reader-comes-with-malware%2F&data=05%7C01%7Cbtozer%40iqt.org%7C7aa5db00e9f94753416508da3994eb6c%7C4e14f559d5ad4de78710d763a7bf84d8%7C0%7C0%7C637885609020958906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rEgxVwNw83Zl0gli8%2FroGw6pbe6AXnRuVFQDBrEG09o%3D&reserved=0>

I think it does. @bentztozer<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbentztozer&data=05%7C01%7Cbtozer%40iqt.org%7C7aa5db00e9f94753416508da3994eb6c%7C4e14f559d5ad4de78710d763a7bf84d8%7C0%7C0%7C637885609020958906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rT%2FNPHNIpDqv%2BrB4Daih63y%2BWquCHDCQ2q79O1Qzg%2Bw%3D&reserved=0> ???

-

**Comment by jspeed-meyers** [comment]
Yes please! Also, did you mean to copy in that info above? I think you can edit the comment.

**Comment by bentztozer** [comment]
Thanks for the heads up, and will do.
