### ISSUE TITLE
Add dependency confusion attacks by Alex Birsan

### ISSUE THREAD

**Issue by jspeed-meyers** [IQTLabs/software-supply-chain-compromises#6]
Need help! Need to add Alex Birsan's dependency confusion attack. Could classify as typosquatting, or could classify as "typosquatting -- dependency confusion" to make this clear this attack is really a sub-type.

Primary source: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

**Comment by bentztozer** [comment]
Added in commit a4526d80de5da4efd27837be325f9732fa2d7e13
