### ISSUE TITLE
Add npm confusion attack copycats

### ISSUE THREAD

**Issue by jspeed-meyers** [IQTLabs/software-supply-chain-compromises#8]
Please help!

Sonatype detected copycats of Alex Birsan's namespace attack on npm.

Original source: https://blog.sonatype.com/sonatype-spots-150-malicious-npm-packages-copying-recent-software-supply-chain-attacks

**Comment by jspeed-meyers** [comment]
Perhaps this should be the link and the number should really be 700: https://blog.sonatype.com/malicious-dependency-confusion-copycats-exfiltrate-bash-history-and-etc-shadow-files

**Comment by bentztozer** [comment]
Added in commit a4526d80de5da4efd27837be325f9732fa2d7e13
